name: Bug Report
description: Report technical issues or unexpected behavior
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Before reporting:**
        - Verify you're using the latest version
        - Check existing issues for duplicates
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS: [e.g. macOS 14.5]
        - Python Version: [e.g. 3.10]
        - Installation Method: [pip/docker]
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Clear steps to reproduce the issue
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
  - type: textarea  
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Include error messages/logs if available
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, configuration details, etc.