name: Feature Request
description: Suggest an idea for MoneyPrinterTurbo
title: "[Feature Request] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Feature Request Guidelines
        Before submitting, please check existing issues to avoid duplicates.
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any other approaches considered?
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or other relevant materials