name: gp-pages
on:
  push:
    branches:
      - main
    paths:
      - 'sites/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.15.0"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i
        working-directory: ./sites
      - name: Build gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm install
          pnpm run docs:build
          cd docs/.vuepress/dist && echo 'moneyprinterturbo.ai' > CNAME && echo ${base} > base.txt
      - name: Deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: sites/docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
